### ISSUE TITLE
inconsistent width of the side bar

### ISSUE THREAD

**Issue by severo** [hyparam/hyperparam-cli#1]
The sidebar width is not consistent over the page loads.

[Screencast from 2024-10-11 12-25-58.webm](https://github.com/user-attachments/assets/fbff7c7d-3a92-438a-a104-b3b9e50acadd)

Also, window resizing makes things worse.

[Screencast from 2024-10-11 15-34-34.webm](https://github.com/user-attachments/assets/f9f836ee-1354-4b43-8882-fb2f487a7176)

**Comment by platypii** [comment]
Probably because nav has a min-width but no max. I can't repro myself? but we should fix this.
