### ISSUE TITLE
upgrade hyparquet to 1.6.0 and hightable to 0.7.1

### ISSUE THREAD

**Issue by severo** [hyparam/hyperparam-cli#59]

**Comment by severo** [comment]
I opened https://github.com/hyparam/hyparquet/pull/44 to fix the types. So: it will be 1.6.1, not 1.6.0

**Comment by platypii** [comment]
Approved hyparquet pr, also just published hightable 0.7.2 with a re-rendering fix.

**Comment by severo** [comment]
Done

**Comment by severo** [comment]
Still missing: upgrade in the demos

**Comment by severo** [comment]
OK, demos updated
