### ISSUE TITLE
Rename ParquetView to TableView, to support CSV and JSONL?

### ISSUE THREAD

**Issue by severo** [hyparam/hyperparam-cli#6]
The Cell component is specific to Parquet, maybe reflect this in the name, and check when routing from the App component?

**Comment by platypii** [comment]
If anything I think ParquetView should rename to TableView. Eventually should support CSV and jsonl too, not just parquet.

**Comment by severo** [comment]
OK, indeed. Renaming the issue.

**Comment by severo** [comment]
OK, I'll better close.
